import sqlite3
with sqlite3.connect("BookInfo.db") as db:
  cursor = db.cursor()
cursor.execute("""CREATE TABLE IF NOT EXISTS Authors(
name text PRIMARY KEY,
placeofbirth text);""")
cursor.execute("""INSERT OR IGNORE into Authors(name, placeofbirth)
VALUES("Agatha Christie", "Torquay")""")
db.commit()
cursor.execute("""INSERT OR IGNORE into Authors(name, placeofbirth)VALUES("Cecelia Ahern", "Dublin")""")
db.commit()
cursor.execute("""INSERT OR IGNORE into Authors(name, placeofbirth)VALUES("J.K.Rowling", "Bristol")""")
db.commit()
cursor.execute("""INSERT OR IGNORE into Authors(name, placeofbirth)VALUES("Oscar Wilde", "Dublin")""")
db.commit()
cursor.execute("""CREATE TABLE IF NOT EXISTS Books(
 id integer PRIMARY KEY,
 Title text NOT NULL,
 Author text NOT NULL,
 datepublished integer);""")
db.commit()
cursor.execute("""INSERT OR IGNORE into Books(id, Title, Author, datepublished)
VALUES("1", "De Profundis", "Oscar Wilde", "1905")""")
db.commit()
cursor.execute("""INSERT OR IGNORE into Books(id, Title, Author, datepublished)
VALUES("2", "Harry Potter and the chamber of secrets", "J.K.Rowling", "1998")""")
db.commit()
cursor.execute("""INSERT OR IGNORE into Books(id, Title, Author, datepublished)
VALUES("3", "Harry potter and the prisoners of Azkaban", "J.K.Rowling", "1999")""")
db.commit()
cursor.execute("""INSERT OR IGNORE into Books(id, Title, Author, datepublished)
VALUES("4", "Lyrebird", "Cecelia Ahern", "2017")""")
db.commit()
cursor.execute("""INSERT OR IGNORE into Books(id, Title, Author, datepublished)
VALUES("5", "Murder on the Orient Express", "Agatha Christie", "1934")""")
db.commit()
cursor.execute("""INSERT OR IGNORE into Books(id, Title, Author, datepublished)
VALUES("6", "Perfect", "Cecelia Ahern", "2017")""")
db.commit()
cursor.execute("""INSERT OR IGNORE into Books(id, Title, Author, datepublished)
VALUES("7", "The marble collector", "Cecelia Ahern", "2016")""")
db.commit()
cursor.execute("""INSERT OR IGNORE into Books(id, Title, Author, datepublished)
VALUES("8", "The murder on the links", "Agatha Christie", "1923")""")
db.commit()
cursor.execute("""INSERT OR IGNORE into Books(id, Title, Author, datepublished)
VALUES("9", "The picture of Dorian Grey", "Oscar Wilde", "1890")""")
db.commit()
cursor.execute("""INSERT OR IGNORE into Books(id, Title, Author, datepublished)
VALUES("10", "The secret adversary", "Agatha Christie", "1921")""")
db.commit()
cursor.execute("""INSERT OR IGNORE into Books(id, Title, Author, datepublished)
VALUES("11", "The seven dials mystery", "Agatha Christie", "1929")""")
db.commit()
cursor.execute("""INSERT OR IGNORE into Books(id, Title, Author, datepublished)
VALUES("12", "The year I meet you", "Cecelia Ahern", "2014")""")
db.commit()
